inherit_from: .rubocop_todo.yml
AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'spec/**/*'
    # Excluded because it's in such a bad state
    - 'lib/supplejack/controllers/helpers.rb'
    - 'lib/supplejack/config.rb'
  DisplayStyleGuide: true
  # prevent bug caused by https://github.com/bbatsov/rubocop/issues/2213 on travis
  # TODO remove
  UseCache: false
Metrics/LineLength:
  Max: 120
Metrics/MethodLength:
  Max: 25
Style/MultilineOperationIndentation:
  Enabled: false
